config/routes.rb
RetroNote::Application.routes.draw do
  
  root :to => 'dashboard#show'
  devise_for :users
  
  resources :teams
  resources :team_members
  resources :retros
  resources :notes
    

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_team
  before_filter :find_team_list, :only => :index

  def index
    @team_members = @team.members
    @requested_members = @team.membership_requests
  end

  def create
    obj = @team.add_user_with_email(params[:team_member][:email], current_user.id)
    if obj[:error]
      flash[:error] = obj[:error]
    elsif obj[:notice]
      flash[:notice] = obj[:notice]
    end  
    redirect_to team_members_path(:team_id => @team.id)
  end

  def destroy
    @team_member = @team.team_members.find_by_user_id(params[:id])
    raise ActiveRecord::RecordNotFound if @team_member.blank?
    @team_member.destroy
    redirect_to team_members_path(:team_id => @team.id), notice: 'Membership successfully canceled.'
  end  
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/index.html.erb
<%= render(:partial => 'shared/project_name') -%>
<div class="block">
  <%= render :partial => "shared/secondary_navigation"  %>
  <div class="content">
    <h2 class="title">Add member</h2>
    <div class="inner">      
      <%= form_for :team_member, :url => team_members_path(:team_id => @team.id), :html => { :class => :form } do |f| -%>
        <div class="group">
          <%= f.label :email, :class => :label %>
          <%= f.text_field :email, :class => 'text_field' %>
          <span class="description">Ex: abc@example.com</span>
        </div>
        <div class="group navform wat-cf">
          <button class="button" type="submit">
             <%= image_tag("/assets/tick.png") %> <%= t("web-app-theme.save", :default => "Save") %>
          </button>
          <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
        	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), teams_path, :class => "text_button_padding link_button" %>
        </div>
      <% end -%>
    </div>
    <h2 class="title">Members</h2>
    <div class="inner">      
      <table class="table">
        <tr>             
          <th><%= t("activerecord.attributes.team.name", :default => t("activerecord.labels.name", :default => "Name")) %></th>
          <th><%= t("activerecord.attributes.team.email", :default => t("activerecord.labels.name", :default => "Email")) %></th>          
          <th class="last">&nbsp;</th>
        </tr>
        <% @team_members.each do |member| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= member.name %></td>
          <td><%= member.email %></td>          
          <td class="last">
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", team_member_path(:id => member.id, :team_id => @team.id), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
    </div>
    <h2 class="title">Requested Members</h2>
    <div class="inner">       
      <table class="table">
        <tr>             
          <th><%= t("activerecord.attributes.team.email", :default => t("activerecord.labels.name", :default => "Email")) %></th>          
          <th class="last">&nbsp;</th>
        </tr>
        <% @requested_members.each do |requested_member| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= requested_member.email %></td>          
          <td class="last">
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", team_member_path(:id =>  requested_member.id, :team_id => @team.id), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>      
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>        
      </div>
    </div>
  </div>
</div>