config/routes.rb
RetroNote::Application.routes.draw do
  
  root :to => 'dashboard#show'
  devise_for :users
  
  resources :teams
  resources :team_members
  resources :retros
  resources :notes
    

end

app/views/shared/_project_name.html.erb
<div class="block">
  <div class="content">
    <h2 class="title"><%= @team.name %></h2>
    <div class="inner">     

      <div class="wat-cf">
        <%= link_to image_tag("/assets/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_team_path(@team), :class => "button" %> 
        <%= link_to image_tag("/assets/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), team_path(@team), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

app/views/shared/_secondary_navigation.html.erb
<div class="secondary-navigation">
  <ul class="wat-cf">
    <li class="first <%= 'active' if ["teams", "retros"].include?(controller.controller_name) %>"><%= link_to "Retros", team_path(:id => @team.id)  %></li>
    <li <%= "class=active" if controller.controller_name == "team_members" %>><%= link_to "Members", team_members_path(:team_id => @team.id) %></li>
  </ul>
</div>

app/views/shared/_sidebar.html.erb
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><%= link_to "Add a new team", new_team_path %></li>
  </ul>
</div>

<div class="block">
  <h3>Teams</h3>
  <ul class="navigation">
    <% @teams.each do |team| -%>
      <li><%= link_to team.name, team_path(team) %></li>
    <% end -%>
  </ul>
</div>

<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>