config/routes.rb
RetroNote::Application.routes.draw do
  
  root :to => 'dashboard#show'
  devise_for :users
  
  resources :teams
  resources :team_members
  resources :retros
  resources :notes
    

end

app/models/retro.rb
class Retro < ActiveRecord::Base
  belongs_to :team
  has_many :notes  
  
  validates_presence_of :title  
end

app/controllers/retros_controller.rb
class RetrosController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_team
  before_filter :find_team_list, :only => :show
  
  def show
    @retro = @team.retros.find(params[:id])
    @success_notes = @retro.notes.where("note_type = ?", "Success")
    @failure_notes = @retro.notes.where("note_type = ?", "Failure")
  end

  def create
    @retro = @team.retros.build(params[:retro])

    respond_to do |format|
      if @retro.save
        format.html { redirect_to team_path(@team.id), notice: 'Retro was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @retro = Retro.find(params[:id])

    respond_to do |format|
      if @retro.update_attributes(params[:retro])
        format.html { redirect_to @retro, notice: 'Retro was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @retro.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @retro = @team.retros.find(params[:id])
    @retro.destroy

    respond_to do |format|
      format.html { redirect_to team_path(@team.id), notice: 'Retro was successfully deleted.' }
      format.json { head :ok }
    end
  end
end

app/helpers/retros_helper.rb
module RetrosHelper
end

app/views/retros/show.html.erb
<%= render(:partial => 'shared/project_name') -%>
<div class="block">
  <%= render :partial => "shared/secondary_navigation"  %>  
  <div class="content">
    <h2 class="title"><%= @retro.title %></h2>    
    <div class="inner">    
      <h3 class="title">Add Note</h3>  
      <%= form_for :note, :url => notes_path(:team_id => @team.id, :retro_id => @retro.id), :html => { :class => :form } do |f| -%>
        <div class="group wat-cf">
          <div class="left">
            <%= f.label :note_type, :class => :label %>
          </div>
          <div class="right">
            <%= f.radio_button :note_type, Note::SUCCESS, :checked => true  %>
            <%= f.label "Success" %>

            <%= f.radio_button :note_type, Note::FAILURE %>
            <%= f.label "Failure" %>       
          </div>
        </div>        
        <div class="group wat-cf">
          <div class="left">
            <%= f.label :description, :class => :label %>
          </div>
          <div class="right">
            <%= f.text_field :description, :class => 'text_field' %>
          </div>
        </div>
        <div class="group wat-cf">
          <div class="left">
            <%= f.label :responsible, :class => :label %>
          </div>
          <div class="right">
            <%= f.text_field :responsible, :class => 'text_field' %>
          </div>
        </div>
        <div class="group wat-cf">
          <div class="left">
            <%= f.label :escalation, :class => :label %>
          </div>
          <div class="right">
            <%= f.text_field :escalation, :class => 'text_field' %>
          </div>
        </div>
        
        <div class="group navform wat-cf">
          <button class="button" type="submit">
             <%= image_tag("/assets/tick.png") %> <%= t("web-app-theme.save", :default => "Save") %>
          </button>
          <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
        	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), teams_path, :class => "text_button_padding link_button" %>
        </div>
      <% end -%>
    </div>
    <h2 class="title">Success</h2>
    <div class="inner">      
      <table class="table">
        <tr>             
          <th>Description</th>
          <th>Responsible</th> 
          <th>Escalation</th>         
          <th class="last">&nbsp;</th>
        </tr>
        <% @success_notes.each do |note| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= note.description %></td>
          <td><%= note.responsible %></td>     
          <td><%= note.escalation %></td>          
          <td class="last">
            <%= link_to "Delete", note_path(:id => note.id, :team_id => @team.id, :retro_id => @retro.id), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
    </div>
    <h2 class="title">Failure</h2>
    <div class="inner">      
      <table class="table">
        <tr>             
          <th>Description</th>
          <th>Responsible</th> 
          <th>Escalation</th>         
          <th class="last">&nbsp;</th>
        </tr>
        <% @failure_notes.each do |note| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= note.description %></td>
          <td><%= note.responsible %></td>     
          <td><%= note.escalation %></td>          
          <td class="last">
            <%= link_to "Delete", note_path(:id => note.id, :team_id => @team.id, :retro_id => @retro.id), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
    </div>
  </div>
</div>